### PR TITLE
[Fix #3893] Fixing serialization issue when using binary mode

### LINKED ISSUE #3893: Fixing byte array compatibility
### Describe the bug

Modified Data index receiving events coming from runtime version previous to the addition of retrigger property fail to deserialize the events if binary mode is enabled 

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by fjtirado**
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3893

### CODE REVIEW

File: api/kogito-events-api/src/main/java/org/kie/kogito/event/process/ProcessInstanceNodeEventBody.java [hunk 1]
```diff
@@ -105,7 +114,9 @@ public void readEvent(DataInput in) throws IOException {
         workItemId = readUTF(in);
         slaDueDate = readDate(in);
         data = (Map<String, Object>) readObject(in);
-        retrigger = (Boolean) readObject(in);
+        if (flags.contains(KogitoMarshallEventFlag.RETRIGGER)) {
```
Comment (fjtirado) [inline api/kogito-events-api/src/main/java/org/kie/kogito/event/process/ProcessInstanceNodeEventBody.java:117]: This is the key change, do not try to read the byte if the cloud event header does not contain the flag

**Review by gmunozfe — APPROVED** [review]
Looks good to me, great work @fjtirado !

**Review by wmedvede — COMMENTED** [review]
+1
