### PR TITLE
[Fix #3390] Fixing patch and retrigger REST APIs

### LINKED ISSUE #3390: Retrigger instance in error state is not working properly
### Describe the bug

Retrigger instance in error state is not working properly

### Expected behavior

The workflow in `ERROR` state is retriggered successfully.

### Actual behavior

The workflow is not retriggered. Instead, you get the following response:
```json
{"message":"Node with definition id _jbpm-unique-508 was not found"}
```

### How to Reproduce?

Test workflow available at https://gist.github.com/caponetto/bae8d02d1f7aa77318f4618dd9e981bb

1. Run the test workflow - it will end up in `ERROR` state
```bash
curl -X POST -H "Content-Type: application/json" http://localhost:8080/wait-or-error -d '{"state": "Error"}'
```
The response will be something like:
```json
{"failedNodeId":"_jbpm-unique-508","id":"3045d54d-35a8-4554-a656-8aebe36466d5","message":"org.kie.kogito.process.workitems.KogitoWorkItemHandlerNotFoundException - Could not find work item handler for actions-openapi_unknown-action"}
```

2. Retrigger the workflow
```bash
curl -X POST -H "Content-Type: application/json" http://localhost:8080/management/processes/wait-or-error/instances/3045d54d-35a8-4554-a656-8aebe36466d5/retrigger
```
The response is:
```json
{"message":"Node with definition id _jbpm-unique-508 was not found"}
```

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by fjtirado**
Fixes https://github.com/apache/incubator-kie-kogito-runtimes/issues/3390
It also fixes PATCH rest API ( it was detected it does not work while testing this PR)

### CODE REVIEW

File: jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/NodeInstanceContainer.java [hunk 1]
```diff
@@ -63,7 +63,7 @@ default NodeInstance getByNodeDefinitionId(final String nodeDefinitionId, NodeCo
         for (Node node : nodeContainer.getNodes()) {
 
             if (nodeDefinitionId.equals(node.getMetaData().get(UNIQUE_ID))) {
-                return getNodeInstance(node);
+                return ((NodeInstanceContainer) getNodeInstance((Node) nodeContainer)).getNodeInstance(node);
```
Comment (fjtirado) [inline jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/NodeInstanceContainer.java:66]: This fixed the NodeNotFoundException. which happens when the failed node is contained within a compositecontexNode. The rest of the PR fixes the patch issue (needed to actually fix the model before retry), which was replacing rather than merging the whole model

**Review by ricardozanini — APPROVED** [review]

**Comment by kie-ci3** [comment]
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3419 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3419/3/display/redirect

**Test results:**
- PASSED: 2339
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3419/3/testReport/org.kie.kogito.quarkus/ServerlessWorkflowCodestartTest/___/">org.kie.kogito.quarkus.ServerlessWorkflowCodestartTest.(?)</a></summary>
java.lang.ExceptionInInitializerError<br/>	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)<br/>	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)<br/>	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42)<br/>	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:185)<br/>	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1132)<br/>	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1113)<br/>	at java.base/java.lang.reflect.Field.get(Field.java:425)<br/>	at org.junit.platform.commons.util.ReflectionUtils.lambda$tryToReadFieldValue$5(ReflectionUtils.java:673)<br/>	at org.junit.platform.commons.function.Try.lambda$call$0(Try.java:57)<br/>	at org.junit.platform.commons.function.Try.of(Try.java:93)<br/>	at org.junit.platform.commons.function.Try.call(Try.java:57)<br/>	at org.junit.platform.commons.util.ReflectionUtils.tryToReadFieldValue(ReflectionUtils.java:673)<br/>	at org.junit.jupiter.engine.descriptor.ExtensionUtils.lambda$registerExtensionsFromFields$4(ExtensionUtils.java:106)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at org.junit.jupiter.engine.descriptor.ExtensionUtils.registerExtensionsFromFields(ExtensionUtils.java:98)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.prepare(ClassBasedTestDescriptor.java:154)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.prepare(ClassBasedTestDescriptor.java:84)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)<br/>	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)<br/>	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:56)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)<br/>Caused by: java.lang.NullPointerException: quarkus version not found in extensions<br/>	at java.base/java.util.Objects.requireNonNull(Objects.java:235)<br/>	at io.quarkus.devtools.testing.codestarts.QuarkusCodestartTestBuilder.setupStandaloneExtensionTest(QuarkusCodestartTestBuilder.java:233)<br/>	at org.kie.kogito.quarkus.ServerlessWorkflowCodestartTest.<clinit>(ServerlessWorkflowCodestartTest.java:36)<br/>	... 58 more<br/>
</details>

**Comment by kie-ci3** [comment]
**PR job** `#5` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3419 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3419/5/display/redirect

**Test results:**
- PASSED: 3226
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3419/5/testReport/org.kie.kogito.quarkus/ServerlessWorkflowCodestartTest/___/">org.kie.kogito.quarkus.ServerlessWorkflowCodestartTest.(?)</a></summary>
java.lang.ExceptionInInitializerError<br/>	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)<br/>	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)<br/>	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42)<br/>	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:185)<br/>	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1132)<br/>	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1113)<br/>	at java.base/java.lang.reflect.Field.get(Field.java:425)<br/>	at org.junit.platform.commons.util.ReflectionUtils.lambda$tryToReadFieldValue$5(ReflectionUtils.java:673)<br/>	at org.junit.platform.commons.function.Try.lambda$call$0(Try.java:57)<br/>	at org.junit.platform.commons.function.Try.of(Try.java:93)<br/>	at org.junit.platform.commons.function.Try.call(Try.java:57)<br/>	at org.junit.platform.commons.util.ReflectionUtils.tryToReadFieldValue(ReflectionUtils.java:673)<br/>	at org.junit.jupiter.engine.descriptor.ExtensionUtils.lambda$registerExtensionsFromFields$4(ExtensionUtils.java:106)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)<br/>	at org.junit.jupiter.engine.descriptor.ExtensionUtils.registerExtensionsFromFields(ExtensionUtils.java:98)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.prepare(ClassBasedTestDescriptor.java:154)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.prepare(ClassBasedTestDescriptor.java:84)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)<br/>	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)<br/>	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:56)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)<br/>Caused by: java.lang.NullPointerException: quarkus version not found in extensions<br/>	at java.base/java.util.Objects.requireNonNull(Objects.java:235)<br/>	at io.quarkus.devtools.testing.codestarts.QuarkusCodestartTestBuilder.setupStandaloneExtensionTest(QuarkusCodestartTestBuilder.java:233)<br/>	at org.kie.kogito.quarkus.ServerlessWorkflowCodestartTest.<clinit>(ServerlessWorkflowCodestartTest.java:36)<br/>	... 58 more<br/>
</details>

**Review by nmirasch — APPROVED** [review]

**Comment by pefernan** [comment]
@fjtirado I think I broke the `ServerlessWorkflowCodestartTest`, give me a min to fix it please.

**Comment by pefernan** [comment]
@fjtirado https://github.com/apache/incubator-kie-kogito-runtimes/pull/3421/files
