### PR TITLE
[Fix #3576] Searching for unique id in recursive way

### LINKED ISSUE #3576: SW - onErrors handler on a compensating state fails validation
### Describe the bug

An onErrors block defined on a compensating operation state fails with a build validation error.

`{
      "name": "CancelItem",
      "type": "operation",
      "usedForCompensation": true,
      "actions": [
        {
          "functionRef": {
            "refName": "cancelItem",
            "arguments": {
              "orderId": ".itemId"
            }
          }
        }
      ],
      "onErrors": [
        {
          "errorRefs": ["ServiceException", "TransportException"],
          "transition": "HandleError"
        }
      ]
    }`

### Expected behavior

Ecpect the compensating state to be able to define an error handler just as any other state.

### Actual behavior

Validation failure:

Found error: {}: java.lang.IllegalArgumentException: Could not find node to attach to: 50
        at org.jbpm.ruleflow.core.RuleFlowProcessFactory.findNodeByIdOrUniqueIdInMetadata(RuleFlowProcessFactory.java:432)
        at org.jbpm.ruleflow.core.RuleFlowProcessFactory.linkBoundaryEvents(RuleFlowProcessFactory.java:301)
        at org.jbpm.ruleflow.core.RuleFlowProcessFactory.link(RuleFlowProcessFactory.java:278)
        at org.jbpm.ruleflow.core.RuleFlowProcessFactory.validate(RuleFlowProcessFactory.java:241)
        at org.kie.kogito.serverless.workflow.parser.ServerlessWorkflowParser.parseProcess(ServerlessWorkflowParser.java:173)
        at org.kie.kogito.serverless.workflow.parser.ServerlessWorkflowParser.getProcessInfo(ServerlessWorkflowParser.java:184)
        at org.kie.kogito.codegen.process.ProcessCodegen.parseWorkflowFile(ProcessCodegen.java:229)
        at org.kie.kogito.codegen.process.ProcessCodegen.lambda$ofCollectedResources$1(ProcessCodegen.java:128)

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

windows 11

### Output of `java -version`

java 17

### GraalVM version (if different from Java)

_No response_

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

999-snapshot

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.6

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by fjtirado**
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3576

### CODE REVIEW

File: jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowProcessFactory.java [hunk 1]
```diff
@@ -420,20 +420,28 @@ protected DroolsAction timerAction(String type) {
...
         }
         return node;
     }
 
+    private Node findNodeByUniqueId(NodeContainer nodeContainer, final String nodeRef) {
+        for (Node containedNode : nodeContainer.getNodes()) {
+            if (nodeRef.equals(containedNode.getUniqueId())) {
+                return containedNode;
+            }
+            if (containedNode instanceof NodeContainer) {
```
Comment (domhanak) [inline jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowProcessFactory.java:435]: @fjtirado Could you please give me a bit of detail of this change here? Why is the extra `instanceof` check here? Looking to understand this better.

**Review by wmedvede — APPROVED** [review]

**Review by domhanak — APPROVED** [review]
