### PR TITLE
[Fix #3995] Overriding ResultHandler for OpenAPIParser

### LINKED ISSUE #3995: RestWorkItemHandler result handling and error codes
### Description

RestworkItemHandler result handling can be customized to usse a different result handler. 
Unfortunately, if error code is different than 200, result handler is never invoked
The check of the status code should be part of the result handler (which by default will throw an exceptionon if error code is different than 2xx)

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by fjtirado**
Fix https://github.com/serverlessworkflow/sdk-java/issues/478

### CODE REVIEW

**Comment by kie-ci3** [comment]
**PR job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3996 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3996/2/display/redirect

**Test results:**
- PASSED: 3383
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3996/2/testReport/org.kie.kogito.codegen.tests/PublishEventIT/testBasicUserTaskProcess/">org.kie.kogito.codegen.tests.PublishEventIT.testBasicUserTaskProcess</a></summary>
<br/>expected: "UserTasksProcess"<br/> but was: "defaultPackage.TimerProcess"
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3996/2/testReport/org.kie.kogito.process.dynamic/DynamicCallResourceTest/testDynamicCallWithInvalidEndpointFormat/">org.kie.kogito.process.dynamic.DynamicCallResourceTest.testDynamicCallWithInvalidEndpointFormat</a></summary>
1 expectation failed.<br/>JSON path message doesn't match.<br/>Expected: a string containing "endpoint invalid-endpoint-format failed"<br/>  Actual: Request failed with message: Not Found<br/>
</details>

File: kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandlerUtils.java [hunk 1]
```diff
@@ -56,6 +60,13 @@ public static <T> Collection<T> getClassListParam(Map<String, Object> parameters
         }
     }
 
+    public static void checkStatusCode(HttpResponse<Buffer> response) {
+        int statusCode = response.statusCode();
+        if (statusCode < 200 || statusCode >= 300) {
+            throw new WorkItemExecutionException(Integer.toString(statusCode), "Request failed with message: " + response.statusMessage());
```
Comment (gmunozfe) [inline kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandlerUtils.java:66]: `response.statusMessage() `may be also null, in that case, you can keep it as it is or add a previous line

`String message = response.statusMessage() != null ? response.statusMessage() : "No status message provided";`

**Review by gmunozfe — APPROVED** [review]
Looks good to me, very good work @fjtirado !

File: kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandlerUtils.java (hunk 1 above)
Comment (fjtirado) [reply kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandlerUtils.java:66]: Good suggestion but I think to print null is fine. It s very rare but if it happens I prefer to see the raw problem.
