### PR TITLE
[Fix #4138] Protocol is not supported in function metadata

### LINKED ISSUE #4138: Protocol is not supported in function metadata
### Describe the bug

The property 
`kogito.sw.functions.<functionname>.protocol=https`
is ignored for a custom rest function. 
This prevents user to use ssl in those functions, unless the full URI is provided in the function definition. 

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by fjtirado**
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/4138

### CODE REVIEW

File: kogito-serverless-workflow/kogito-serverless-workflow-rest-parser/src/main/java/org/kie/kogito/serverless/workflow/parser/types/RestTypeHandler.java [hunk 1]
```diff
@@ -66,6 +66,7 @@ public class RestTypeHandler extends WorkItemTypeHandler {
                 .workParameter(RestWorkItemHandler.METHOD, method)
                 .workParameter(RestWorkItemHandler.USER, runtimeRestApi(functionDef, USER_PROP, context.getContext()))
                 .workParameter(RestWorkItemHandler.PASSWORD, runtimeRestApi(functionDef, PASSWORD_PROP, context.getContext()))
+                .workParameter(RestWorkItemHandler.PROTOCOL, runtimeRestApi(functionDef, "protocol", context.getContext()))
```
Comment (fjtirado) [inline kogito-serverless-workflow/kogito-serverless-workflow-rest-parser/src/main/java/org/kie/kogito/serverless/workflow/parser/types/RestTypeHandler.java]: This is the change that was needed to support protocol property. 
The rest of changes were intended to infer the protocol from port 443 if this port is explicitly set but not protocol is set

File: kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandler.java [hunk 2]
```diff
@@ -162,28 +164,24 @@ public Optional<WorkItemTransition> activateWorkItemHandler(KogitoWorkItemManage
...
-            port = getParam(parameters, PORT, Integer.class, isSsl ? DEFAULT_SSL_PORT : DEFAULT_PORT);
-            logger.debug("Port not specified, using {}", port);
+            port = getParam(parameters, PORT, Integer.class, isHttps(protocol) ? DEFAULT_SSL_PORT : DEFAULT_PORT);
         }
         if (isEmpty(path)) {
             path = endPoint;
             logger.debug("Path is empty, using whole endpoint {}", endPoint);
         }
+        if (isEmpty(protocol)) {
+            protocol = port == DEFAULT_SSL_PORT ? HTTPS_PROTOCOL : HTTP_PROTOCOL;
```
Comment (fjtirado) [inline kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandler.java]: This infers the protocol (if not specified) from the specified port.

**Comment by kie-ci3** [comment]
**PR job** `#6` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/4139 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-4139/6/display/redirect

**Test results:**
- PASSED: 3691
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-4139/6/testReport/org.kie.kogito.integrationtests.quarkus/TaskIT/testUpdateTaskInfo/">org.kie.kogito.integrationtests.quarkus.TaskIT.testUpdateTaskInfo</a></summary>
1 expectation failed.<br/>Expected status code <403> but was <200>.<br/>
</details>
