### PR TITLE
[incubator-kie-issues#2283] Fix `TaskIT` test to ensure it tests the User Tasks created by the associated process instance

### LINKED ISSUE #2283: Fix `TaskIT` test to ensure it tests the User Tasks created by the associated process instance
TaskIT test `randomly` fails on CI when trying to update the task information. Looking at the test, it seems that the test is trying to operate with task instances created in other IT tests in the same project (eg ProcessIT) that are not being cleared.

In this issue I'll try to ensure that the TaskIT test is performing the test in the tasks created in the same test using json path and also clear active process instances at the end of each test.

### PR DESCRIPTION
**Pull request by pefernan**
Closes https://github.com/apache/incubator-kie-issues/issues/2283

Many thanks for submitting your Pull Request :heart:! 

Closes/Fixes/Resolves #ISSUE-NUMBER

**Description:**

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/apache/incubator-kie-kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `Issue-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] Issue-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

### CODE REVIEW

**Review by gitgabrio — APPROVED** [review]
Thx @pefernan !!!!

**Review by yesamer — APPROVED** [review]

File: quarkus/integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/BasicRestIT.java [hunk 1]
```diff
@@ -128,6 +128,13 @@ void testWithInaccurateModel() {
                 .statusCode(200);
 
         assertExpectedUnitOfWorkEvents(1);
+
+        given()
```
Comment (jstastny-cz) [inline quarkus/integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/BasicRestIT.java]: If this test fails on earlier assert then the problem is still present, right? That might create clustered test failures, which might be hard to investigate.

Would it be possible to have in an after method? I think it would either require to get all existing instances, or at least try deleting based on a class field holding the process id - but each test would need to set that field accordingly for the after method to read properly :/ And then it should not validate status code perhaps .. kinda complicated for what problem it solves.

**Review by cimbalek — COMMENTED** [review]
Thanks for fixing this!
