### PR TITLE
[Fix_3818] Wrong calculation in test rollCalendarAfterHolidays if day is near to end-of-year

### LINKED ISSUE #3818: Wrong calculation in test rollCalendarAfterHolidays if day is near to end-of-year
### Describe the bug

Notice that the test BusinessCalendarImplTest#rollCalendarAfterHolidays has a wrong calculation if it is run near the year's end, as `currentDayOfYear + holidayLeft ` will exceed 365 (or 366 in a leap year), and the test is not taken this into account

### Expected behavior

The test should consider the year rollover if the sum of `currentDayOfYear + holidayLeft ` exceeds the maximum number of days in a year (366 in a leap year or 365 in a normal year)

### Actual behavior

org.opentest4j.AssertionFailedError: 

expected: 367
 but was: 1
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at org.jbpm.process.core.timer.BusinessCalendarImplTest.rollCalendarAfterHolidays(BusinessCalendarImplTest.java:238)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

### How to Reproduce?

Execute the test:
`mvn clean install -Dtest=BusinessCalendarImplTest#rollCalendarAfterHolidays`

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### GraalVM version (if different from Java)

_No response_

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

_No response_

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gmunozfe**
Many thanks for submitting your Pull Request :heart:! 

Closes/Fixes/Resolves #3818

**Description:** Wrong calculation in test rollCalendarAfterHolidays if day is near to end-of-year

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

### CODE REVIEW

**Review by fjtirado — APPROVED** [review]

File: jbpm/jbpm-flow/src/test/java/org/jbpm/process/core/timer/BusinessCalendarImplTest.java [hunk 1]
```diff
@@ -233,8 +233,12 @@ void rollCalendarAfterHolidays() {
         List<Integer> weekendDays = Collections.emptyList();
         Calendar calendar = Calendar.getInstance();
         int currentDayOfYear = calendar.get(Calendar.DAY_OF_YEAR);
+        int maxDaysInYear = calendar.getActualMaximum(Calendar.DAY_OF_YEAR);
         BusinessCalendarImpl.rollCalendarAfterHolidays(calendar, holidays, weekendDays, false);
         int expected = currentDayOfYear + holidayLeft + 1;
+        if (expected > maxDaysInYear) {
+            expected -= maxDaysInYear;
+        }
```
Comment (pibizza) [inline jbpm/jbpm-flow/src/test/java/org/jbpm/process/core/timer/BusinessCalendarImplTest.java:241]: I understand the patch, but I think the test is wrong. Having an if in a test to define expected values is kind of a code smell. we should know what to expect in a test. If I understsand correclty, the issue here is that the test is not using a fixed day, but instead taking the day we are executing the test.

It is sensible to test the roll of the date, but this means we need two tests - one near the end of the year and one far from the end of the year. I suggest modifying the tests according.

Comment (gmunozfe) [reply jbpm/jbpm-flow/src/test/java/org/jbpm/process/core/timer/BusinessCalendarImplTest.java]: Good point @pibizza ! I've changed to have 2 tests, with and without year rollover and setting also the year for not depending on the year (if it is or not leap year)

**Comment by kie-ci3** [comment]
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3819 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3819/3/display/redirect

**Test results:**
- PASSED: 3524
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3819/3/testReport/org.jbpm.bpmn2/IntermediateEventTest/testIntermediateCatchEventTimerCycle3/">org.jbpm.bpmn2.IntermediateEventTest.testIntermediateCatchEventTimerCycle3</a></summary>
<br/>expected: 3<br/> but was: 2
</details>

**Review by ricardozanini — APPROVED** [review]

**Review by pibizza — APPROVED** [review]
Looks good to me. Note that at this point we could go with just a parameterized test, but we can move this forward.
